version: '3.6'

volumes:
  app:
  db_data:

services:
  app:
    image: wscandy/wordpress
    volumes:
      - app:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_USER: user
      DB_PASSWORD: password
  db:
    image: mysql:5.6
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  nginx:
    image: propcom/nginx:1.0.1
    depends_on:
      - app
    volumes:
      - app:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080